//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingKirill
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bearEntities : DbContext
    {
        public bearEntities()
            : base("name=bearEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Адрес> Адрес { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<ЕдиницыИзмерения> ЕдиницыИзмерения { get; set; }
        public virtual DbSet<ЗаявкаСнабжение> ЗаявкаСнабжение { get; set; }
        public virtual DbSet<Категории> Категории { get; set; }
        public virtual DbSet<Контрагенты> Контрагенты { get; set; }
        public virtual DbSet<НаселПункт> НаселПункт { get; set; }
        public virtual DbSet<Поступления> Поступления { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<СписокПозиций> СписокПозиций { get; set; }
        public virtual DbSet<Статус> Статус { get; set; }
        public virtual DbSet<Товар> Товар { get; set; }
        public virtual DbSet<Улица> Улица { get; set; }
    }
}
