//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingKirill
{
    using System;
    using System.Collections.Generic;
    
    public partial class Адрес
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Адрес()
        {
            this.ЗаявкаСнабжение = new HashSet<ЗаявкаСнабжение>();
        }
    
        public int ИД_Адрес { get; set; }
        public int ИД_НаселПункт { get; set; }
        public int ИД_Улица { get; set; }
        public string Дом { get; set; }
        public string Подъезд { get; set; }
        public string Телефон { get; set; }
        public string КонтактноеЛицо { get; set; }
    
        public virtual НаселПункт НаселПункт { get; set; }
        public virtual Улица Улица { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗаявкаСнабжение> ЗаявкаСнабжение { get; set; }
    }
}
