//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingKirill
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаявкаСнабжение
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ЗаявкаСнабжение()
        {
            this.СписокПозиций = new HashSet<СписокПозиций>();
            this.Поступления = new HashSet<Поступления>();
        }
    
        public int ЗаявкаСнабж_ИД { get; set; }
        public int СотрудникСоздатель_ИД { get; set; }
        public System.DateTime ДатаСоздания { get; set; }
        public string НомерЗаявки { get; set; }
        public int Статус_ИД { get; set; }
        public string Комментарий { get; set; }
        public bool ТоварСписан { get; set; }

        public string ТоварСписанТекст { get{ return ТоварСписан ? "Да" : "Нет"; } }

		public int Адрес_ИД { get; set; }
    
        public virtual Адрес Адрес { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СписокПозиций> СписокПозиций { get; set; }
        public virtual Статус Статус { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Поступления> Поступления { get; set; }
    }
}
