//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingKirill
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поступления
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Поступления()
        {
            this.СписокПозиций = new HashSet<СписокПозиций>();
        }
    
        public int Поступления_ИД { get; set; }
        public int СотрудникСоздатель_ИД { get; set; }
        public System.DateTime ДатаСоздания { get; set; }
        public string Комментарий { get; set; }
        public string НомерПоступления { get; set; }
        public bool УчтеноНаСкладе { get; set; }
        public string УчтеноНаСкладеТекст { get{return УчтеноНаСкладе ? "Да" : "Нет"; } }
        public Nullable<int> ЗаявкаСнабж_ИД { get; set; }
        public int Статус_ИД { get; set; }
    
        public virtual ЗаявкаСнабжение ЗаявкаСнабжение { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СписокПозиций> СписокПозиций { get; set; }
        public virtual Статус Статус { get; set; }
    }
}
