//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingKirill
{
    using System;
    using System.Collections.Generic;
    
    public partial class СписокПозиций
    {
        public int Чек_ИД { get; set; }
        public Nullable<int> Поступления_ИД { get; set; }
        public Nullable<int> ЗаявкаСнабж_ИД { get; set; }
        public int Товар_ИД { get; set; }
        public float Количество { get; set; }
        public Nullable<decimal> Цена_Ед { get; set; }
    
        public virtual ЗаявкаСнабжение ЗаявкаСнабжение { get; set; }
        public virtual Поступления Поступления { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
