//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingKirill
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товар()
        {
            this.СписокПозиций = new HashSet<СписокПозиций>();
        }
    
        public int Товар_ИД { get; set; }
        public string Наименование { get; set; }
        public int Категории_ИД { get; set; }
        public decimal СтоимостьПокупки { get; set; }
        public float Остаток { get; set; }
        public Nullable<int> ОсновнойПоставщик { get; set; }
        public Nullable<int> ЕдИзм_ИД { get; set; }
    
        public virtual ЕдиницыИзмерения ЕдиницыИзмерения { get; set; }
        public virtual Категории Категории { get; set; }
        public virtual Контрагенты Контрагенты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СписокПозиций> СписокПозиций { get; set; }
    }
}
